### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Chonghui-Liu** [phillipnicol/scDist#15]
Hello,

When I used your function scDist, I encountered the following error:
================================================================================
Warning in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Warning in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Error in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE) : 
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))
Could you please share your thoughts on this error?

**Comment by phillipnicol** [comment]
Hi,

This error usually occurs when the number of PCs used is larger than the number of cells of some cell type. Are you using the default parameter values for `min.count.per.cell` and `d`? If not, you can try setting `min.count.per.cell` to be say twice the value of `d`. Let me know if this helps.

**Comment by Chonghui-Liu** [comment]
Hello,

Thank you very much for your suggestion! You were absolutely correct—I reduced the value of the d parameter as you recommended, and the scDist method no longer shows an error.

However, I have another question I’d like to ask. In the scDist_result$results output, I noticed that all values in the Dist. column are 0, and all p.val values are greater than 0.05. Does this mean that no cell type shows significant differences between the two conditions?

Thank you again for your help!

![Snipaste_2024-11-07_10-54-12](https://github.com/user-attachments/assets/69944f5e-854c-4df3-bf04-7a83a9255874)

**Comment by phillipnicol** [comment]
Yes that is what it is indicating here. How many patient/samples do you have? When there are a very small number of patients I have found that it is sometimes beneficial to control for patient in the `fixed.effects` argument, see my response to issue #4 for additional details here.

**Comment by Chonghui-Liu** [comment]
Thank you very much for your patient and detailed guidance. My single-cell data does indeed come from a small number of samples—specifically, only 4 samples (2 patient samples and 2 healthy samples).

Following your advice, I modified my code from:

scDist_result <- scDist(as.matrix(sc_data@assays$RNA@scale.data),
                          sc_data@meta.data,
                          fixed.effects = "source_phen",
                          random.effects="patient",
                          clusters="seurat_clusters",
                          d=8)

to:

scDist_result <- scDist(as.matrix(sc_data@assays$RNA@scale.data),
                sc_data@meta.data,
                fixed.effects = c("source_phen", "patient"),
                clusters="seurat_clusters",
                d=8)
                
 With this adjustment, I obtained new results, indicating that cell type “3” is now identified as a significant cell type with a low p-value. Could you please confirm if this approach is correct?
![Snipaste_2024-11-07_21-09-48](https://github.com/user-attachments/assets/1014e5a6-8d53-43aa-85b7-5ee6fad64e1a)

Thank you again for all your help!

**Comment by phillipnicol** [comment]
Yes, that is the correct interpretation! 

In general, with a small number of samples (2 vs 2) there may not be enough statistical power to identify significantly different cell types, which is why it is not unusual to see many distance estimates of 0 in this case.
